# Generated by Django 4.2 on 2023-04-24 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload_img',
            old_name='img',
            new_name='patient_image',
        ),
    ]
